#pragma once

#include <string>


const int numOfProps = 35;
const int numOfEnemies = 20;

std::string mapLayout[numOfProps]{
	"  x  xx                            ",
	"                                   ",
	"                                   ",
	"                 x       b xxx     ",
	"                        b xx       ",
	"                       b xx        ",
	"                       b xx        ",
	"                 xx xxxb x         ",
	"                    x xb x         ",
	"      xxxx             b x         ",
	"        b              b x         ",
	"                    xxxb x         ",
	"                       b x         ",
	"                    x b xx         ",
	"                    xb xx          ",
	"                    b xx           ",
	"                 bbb xx            ",
	"    xbb        sb b xxx            ",
	"    xx bbbbbbbb x b xxx            ",
	"      bbbbbbx  xx b xx             ",
	"                 b xxxx            ",
	"                b xxxxx            ",
	"               b x  o x            ",
	"               b x   xx            ",
	"             b xxx  xxx            ",
	"            b xxx    xx            ",
	"       b    b xxo                  ",
	"            b x      xxx           ",
	"           b xx       xx           ",
	"       s  b xx      xxx            ",
	"        b xx                       ",
	"      xb xxx        xxx            ",
	"                                   ",
	"                                   ",
	"                                   "
};

std::string mapDungeonLayout[numOfProps]{
	"                                   ",
	"                                   ",
	"                                   ",
	"                  b                ",
	"    xwxwxxxxwwwxxxxwwwwxwwxxwwwxx  ",
	"    wxwwxxwwwwwxwwwwwwwxwwxwxwwxx  ",
	"    wwwwwwwwwwwwwxxxxwxwxw      x  ",
	"    wxxxwxxwwwwwwxxxxxwww       w  ",
	"    x                      xww  w  ",
	"    x                      x    x  ",
	"    x  xbb    b            wwx  w  ",
	"    w  wbbbb          ww        w  ",
	"    w  wxxxwwxbwwxxw  wxw       x  ",
	"    w  x       x      xwwwxxwwwxx  ",
	"    w  x   bb  x       wwwwxxwxww  ",
	"    x  x   b   w       xwxxxwwwxx  ",
	"    w  w       w       wwwwwwwwww  ",
	"    x  w       w       wwwwwwwwww  ",
	"    x  w       wwxwwwwxxxxxwwwxww  ",
	"    w  xwwxwwwxxwwxxxwxwwxxwwxwww  ",
	"    x          wwwxxxwwxbbbbbbbbx  ",
	"    w                        bbbw  ",
	"    x                 b        bx  ",
	"    w                           w  ",
	"    w            b              x  ",
	"    w                           w  ",
	"    x      xwxwxwxwxwwxw        x  ",
	"    x      wwxwxwwwwwwww        x  ",
	"    xxwwxxwwwxxxxwwwwxxx        w  ",
	"    wb     wwxxwxwwwxwww        w  ",
	"    x                           w  ",
	"    w                           w  ",
	"    w      wwwwwwwwwwwwwb       w  ",
	"    xwxwxxxxwwwxxxxwwwwxwwxxwwwxx  ",
	"                                   "
};

std::string mapLayoutEnemies[numOfProps]{
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                          s        ",
	"        xxxxx            o         ",
	"                                   ",
	"                          s        ",
	"                                   ",
	"                                   ",
	"     o                             ",
	"     s              os             ",
	"     x                             ",
	"                  s  ss            ",
	"                                   ",
	"                                   ",
	"                                   ",
	"                                   ",
	"     o                             ",
	"                                   ",
	"                   osx             ",
	"                    x         xx   ",
	"      oss                          ",
	"                             ss    ",
	"                                   ",
	"                             xxxx  ",
	"                                   ",
	"              o              oo    ",
	"         xx                        ",
	"        os                     x   ",
	"                                   ",
	"                                   "
};
